name:                kmeans
version:             0.1.0.0
github:              "zdavep/kmeans"
license:             BSD3
author:              "David Pederson"
maintainer:          "dave.pederson@gmail.com"
copyright:           "2020-present, the original author(s)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zdavep/kmeans#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- DeriveGeneric

library:
  source-dirs: src
  dependencies:
  - binary
  - bytestring
  - deepseq
  - vector

executables:
  kmeans-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kmeans
    - binary
    - parallel
    - time

tests:
  kmeans-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kmeans
